name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.14"
      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      - run: uv sync --frozen --no-default-groups --group=check
      - run: uv run --frozen --no-default-groups --group=check ruff format --check src tests scripts
      - run: uv run --frozen --no-default-groups --group=check ruff check src/postgresbuild tests scripts pyproject.toml
      - run: uv run --frozen --no-default-groups --group=check mypy
      - run: uv run --frozen --no-default-groups --group=check ty check
      - run: uv run --frozen --no-default-groups --group=check zizmor --offline .github/workflows
      - run: uv run --frozen --no-default-groups --group=check ggbuild ci check-workflow

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.14"
      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      - run: uv sync --frozen --no-default-groups --group=test
      - run: uv run --frozen --no-default-groups --group=test ggt tests
